#!/bin/bash

echo "🚀 GarageManager Pro - Render Deployment Guide"
echo "=============================================="
echo ""

echo "📋 Pre-deployment Checklist:"
echo "✅ Ensure your code is pushed to GitHub"
echo "✅ Ensure render.yaml is in your repository root"
echo "✅ Have your environment variables ready"
echo ""

echo "🔧 Manual Steps Required:"
echo ""
echo "1. Go to https://render.com and sign in"
echo "2. Click 'New +' and select 'Web Service'"
echo "3. Connect your GitHub repository: kaiteddy/v0dashboard"
echo "4. Configure the service:"
echo "   - Name: garagemanager-pro"
echo "   - Environment: Node"
echo "   - Build Command: npm ci && npm run build"
echo "   - Start Command: npm start"
echo "   - Plan: Starter (or higher)"
echo ""

echo "🔐 Environment Variables to Set in Render Dashboard:"
echo "   - DATABASE_URL=your_neon_database_url"
echo "   - NEXTAUTH_SECRET=your_nextauth_secret"
echo "   - TWILIO_ACCOUNT_SID=your_twilio_sid"
echo "   - TWILIO_AUTH_TOKEN=your_twilio_token"
echo "   - TWILIO_PHONE_NUMBER=your_twilio_number"
echo "   - TWILIO_WHATSAPP_NUMBER=your_whatsapp_number"
echo "   - MINIMAX_API_KEY=your_minimax_key"
echo "   - DVLA_API_KEY=your_dvla_key"
echo "   - DVSA_CLIENT_ID=your_dvsa_client_id"
echo "   - DVSA_CLIENT_SECRET=your_dvsa_client_secret"
echo ""

echo "🚨 Common Render Issues & Solutions:"
echo ""
echo "1. Build Timeout:"
echo "   - Increase build timeout in Render settings"
echo "   - Use npm ci instead of npm install"
echo "   - Consider upgrading to a higher plan"
echo ""
echo "2. Memory Issues:"
echo "   - Add NODE_OPTIONS=--max-old-space-size=4096"
echo "   - Upgrade to a plan with more memory"
echo ""
echo "3. Database Connection:"
echo "   - Ensure DATABASE_URL includes ?sslmode=require"
echo "   - Check if your database allows external connections"
echo ""
echo "4. Static Files:"
echo "   - Ensure public folder is included in build"
echo "   - Check Next.js output configuration"
echo ""

echo "📊 Monitoring & Debugging:"
echo "   - Check build logs in Render dashboard"
echo "   - Monitor runtime logs for errors"
echo "   - Use Render's built-in metrics"
echo ""

echo "🔗 Useful Links:"
echo "   - Render Dashboard: https://dashboard.render.com"
echo "   - Render Docs: https://render.com/docs"
echo "   - Next.js on Render: https://render.com/docs/deploy-nextjs-app"
echo ""

echo "✅ Once deployed, your app will be available at:"
echo "   https://garagemanager-pro.onrender.com (or similar)"
